<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        @page { margin: 0px; }
        body { font-family: Helvetica, sans-serif; margin: 0; padding: 0; color: #0c2f5a; }
        
        /* 1. THE STATUS RIBBON */
        .ribbon-box {
            position: absolute; top: 0; right: 0;
            width: 150px; height: 150px; overflow: hidden;
        }
        .ribbon {
            position: absolute; top: 30px; right: -50px; width: 200px;
            transform: rotate(45deg); text-align: center; color: #fff;
            font-weight: bold; padding: 8px 0; font-size: 16px;
        }
        .paid { background: #148c14; }
        .unpaid { background: #ef4444; }

        /* 2. LOCKED FOOTER (Bottom 25% of page) */
        .fixed-footer {
            position: absolute; bottom: 0; width: 100%;
        }

        /* 3. GRID LAYOUTS */
        .main-container { padding: 40px 50px; }
        .layout-table { width: 100%; border-collapse: collapse; }
        
        .product-table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        .product-table th { background: #0c2f5a; color: #fff; padding: 12px; text-align: left; }
        .product-table td { background: #f2f2f2; padding: 12px; border-bottom: 8px solid #fff; }

        .totals-table { width: 100%; border-collapse: collapse; }
        .totals-table td { padding: 5px 0; font-size: 13px; }
        .balance-due { border-top: 2px solid #000; font-weight: bold; font-size: 16px; }
        
        .accent-bar { height: 46px; background: #0c2f5a; position: relative; }
        .gold-curve { 
            position: absolute; left: 0; top: 0; width: 35%; height: 46px; 
            background: #d18b54; border-top-right-radius: 60px; 
        }
    </style>
</head>
<body>

<div class="ribbon-box">
    <div class="ribbon {{ $order->payment_status === 'paid' ? 'paid' : 'unpaid' }}">
        {{ strtoupper($order->payment_status) }}
    </div>
</div>

<div class="main-container">
    <table class="layout-table">
        <tr>
            <td style="width: 60%;">
                <img src="{{ resource_path('images/logo.png') }}" style="width: 100px;">
                <p style="font-size: 12px; margin-top: 15px;">
                    Show Room: G.floor BBS Mall, 12st Eastleigh Nairobi<br>
                    Office: Decale palace hotel 2nd floor 12st, Eastleigh<br>
                    Email: Info@orbitakenya.com
                </p>
            </td>
            <td style="text-align: right; vertical-align: top;">
                <h1 style="font-size: 40px; color: #d18b54; margin: 0;">INVOICE</h1>
                <p style="font-size: 13px; margin: 10px 0 0 0;">
                    Date: <strong>{{ $order->created_at->format('m/d/Y') }}</strong><br>
                    No.# <strong>#{{ $order->order_number }}</strong>
                </p>
            </td>
        </tr>
    </table>

    <div style="height: 2px; background: #d18b54; margin: 20px 0;"></div>

    <table class="layout-table" style="font-weight: bold; font-size: 14px;">
        <tr>
            <td>INVOICED TO: {{ strtoupper($order->shipping_address) }}</td>
            <td style="text-align: right;">GENERATED BY: {{ strtoupper($order->staff_name ?? 'OGACHI') }}</td>
        </tr>
    </table>

    <div style="height: 1px; background: #eee; margin: 15px 0;"></div>

    <table class="product-table">
        <thead>
            <tr>
                <th style="width: 50%;">PRODUCT</th>
                <th style="text-align: center;">PRICE</th>
                <th style="text-align: center;">QTY</th>
                <th style="text-align: right;">TOTAL</th>
            </tr>
        </thead>
        <tbody>
            @foreach($order->items as $item)
            <tr>
                <td>{{ $item->product->name }}</td>
                <td style="text-align: center;">{{ number_format($item->unit_price, 2) }}</td>
                <td style="text-align: center;">{{ $item->quantity }}</td>
                <td style="text-align: right;">{{ number_format($item->unit_price * $item->quantity, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>

<div class="fixed-footer">
    <table class="layout-table" style="padding: 0 50px 20px 50px;">
        <tr>
            <td style="width: 50%; vertical-align: top; font-size: 12px;">
                <strong>BANKING DETAILS</strong><br>
                CO-OPERATIVE BANK ACC<br>
                NAME: ORBITAHTECH SYSTEMS KENYA LTD.<br>
                ACC: 01100542859001
            </td>
            <td style="width: 50%;">
                <table class="totals-table">
                    <tr><td>SUBTOTAL :</td><td style="text-align: right;">{{ number_format($order->subtotal, 2) }}</td></tr>
                    <tr><td>DISCOUNT (40%) :</td><td style="text-align: right;">-{{ number_format($order->subtotal * 0.40, 2) }}</td></tr>
                    <tr><td>VAT (16%) :</td><td style="text-align: right;">{{ number_format(($order->subtotal * 0.60) * 0.16, 2) }}</td></tr>
                    <tr class="balance-due">
                        <td>BALANCE DUE:</td>
                        <td style="text-align: right;">KSH. {{ number_format($order->grand_total, 2) }}</td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>

    <div style="padding: 0 50px 15px 50px; font-size: 10px;">
        <strong>TERMS:</strong> 1 Year warranty on manufacturing defects. Ownership remains with Orbita Kenya until full payment.
    </div>

    <table class="layout-table" style="text-align: center; font-size: 11px; padding: 15px 50px; border-top: 1px solid #eee;">
        <tr>
            <td><strong>TEL:</strong> +254 726 777 733</td>
            <td><strong>WEB:</strong> www.orbitakenya.com</td>
            <td><strong>LOC:</strong> BBS Mall, Eastleigh</td>
        </tr>
    </table>

    <div class="accent-bar">
        <div class="gold-curve"></div>
        <div style="width: 100%; text-align: center; line-height: 46px; color: #fff; font-size: 11px; position: relative;">
            This invoice is system-generated by Orbita Kenya
        </div>
    </div>
</div>

</body>
</html>