@php
    $settings = \App\Models\ShopSetting::first();

    // --- 1. SETTINGS & FALLBACKS ---
    $showroom = $settings->shop_address ?? 'G.floor BBS Mall, 12st Eastleigh Nairobi, Kenya';
    $office = $settings->office_address ?? 'Decale palace hotel 2nd floor 12st, Eastleigh, Nairobi';
    $email = $settings->email_contact ?? 'info@orbitakenya.com';
    $phone = $settings->phone_contact ?? '+254-726-777-733';
    $bankName = $settings->bank_name ?? 'CO-OPERATIVE BANK';
    $accName = $settings->account_name ?? 'ORBITAHTECH SYSTEMS KENYA LTD.';
    $accNumber = $settings->account_number ?? '01100542859001';
    $generatedBy = auth()->user()->name ?? 'System Admin';

    // --- 2. LOGO LOGIC (The "Cleaner") ---
    $logoData = null;
    $rawPath = $settings->logo_path;

    // Check if it's stored as a JSON string/Array (Filament quirk)
    if (is_string($rawPath) && (str_contains($rawPath, '["') || str_contains($rawPath, '[\"'))) {
        $decoded = json_decode($rawPath, true);
        if (is_array($decoded)) {
            $rawPath = reset($decoded); // Grab the first item
        }
    }
    // Handle if it's already an array (in case model casting is on)
    elseif (is_array($rawPath)) {
        $rawPath = reset($rawPath);
    }

    // Now process the clean path
    if (!empty($rawPath) && $rawPath !== '[]') {
        $fullPath = storage_path('app/public/' . $rawPath);
        
        if (file_exists($fullPath)) {
            $type = pathinfo($fullPath, PATHINFO_EXTENSION);
            $data = file_get_contents($fullPath);
            $logoData = 'data:image/' . $type . ';base64,' . base64_encode($data);
        }
    }

    // --- 3. CALCULATIONS ---
    $subtotal = $order->items->sum(fn($item) => $item->unit_price * $item->quantity);
    $vatRate = $settings->vat_percentage ?? 16; 
    $discountAmount = 0.00;
    $taxableAmount = $subtotal - $discountAmount;
    $taxAmount = $taxableAmount * ($vatRate / 100);
    $shipping = $order->shipping_cost ?? 0.00; 
    $shippingMethod = $order->shipping_method ?? 'Standard Delivery';
    $grandTotal = $taxableAmount + $taxAmount + $shipping;
@endphp

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice #{{ $order->order_number }}</title>
    <style>
        @page { margin: 0px; }
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            margin: 0;
            padding: 40px 50px 0 50px; /* Top padding for header */
            color: #1a2b4b; /* Orbita Blue */
            font-size: 12px;
            background: #fff;
        }

        /* --- UTILITIES --- */
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .text-bold { font-weight: bold; }
        .uppercase { text-transform: uppercase; }
        .c-gold { color: #d48d56; }
        
        table { width: 100%; border-collapse: collapse; }
        
        /* --- HEADER --- */
        .header-table td { vertical-align: top; }
        .logo-img { height: 60px; max-width: 200px; margin-bottom: 10px; }
        .company-info p { margin: 2px 0; font-size: 11px; color: #555; }
        
        .invoice-title {
            font-size: 32px; font-weight: bold; color: #d48d56;
            text-transform: uppercase; margin-bottom: 5px;
        }
        .invoice-meta p { margin: 2px 0; font-size: 12px; }

        /* --- INFO BAR (Invoiced To / Generated By) --- */
        .info-bar { margin-top: 20px; border-top: 2px solid #d48d56; border-bottom: 2px solid #d48d56; padding: 10px 0; }
        .label { font-size: 10px; color: #888; text-transform: uppercase; letter-spacing: 1px; }
        .value { font-size: 13px; font-weight: bold; color: #000; text-transform: uppercase; }

        /* --- PRODUCT TABLE --- */
        .product-table { margin-top: 20px; width: 100%; }
        .product-table th {
            background-color: #1a2b4b; color: #fff;
            padding: 8px 10px; text-transform: uppercase; font-size: 11px; text-align: left;
        }
        .product-table td {
            padding: 10px; border-bottom: 1px solid #eee; color: #444;
        }
        .product-table tr:nth-child(even) { background-color: #f9f9f9; }

        /* --- FIXED FOOTER SECTION --- */
        .footer-wrapper {
            position: fixed;
            bottom: 40px; /* Space for the bottom bar */
            left: 50px;
            right: 50px;
            height: auto;
        }

        /* Bank & Totals Grid */
        .bank-box {
            background: #f3f4f6; border-left: 4px solid #d48d56;
            padding: 10px 15px; font-size: 11px; line-height: 1.6; color: #444;
        }
        
        .totals-table td { padding: 4px 0; font-size: 12px; }
        .grand-total { 
            border-top: 2px solid #1a2b4b; border-bottom: 2px solid #1a2b4b;
            font-size: 14px; font-weight: bold; color: #1a2b4b; padding: 8px 0;
        }

        /* Terms & Divider */
        .divider-line { border-bottom: 1px solid #ddd; margin: 15px 0; }
        .terms-text { font-size: 9px; color: #777; text-align: justify; line-height: 1.3; margin-bottom: 10px; }

        /* Bottom Bar */
        .bottom-bar {
            position: fixed; bottom: 0; left: 0; right: 0;
            height: 30px; background: #1a2b4b; color: #fff;
            text-align: center; line-height: 30px; font-size: 9px; text-transform: uppercase; letter-spacing: 1px;
        }
        
        /* Ribbon */
        .ribbon {
            position: absolute; top: 0; right: 0; width: 100px; height: 100px; overflow: hidden;
        }
        .ribbon-content {
            position: absolute; top: 20px; right: -30px; width: 150px;
            background: #009933; color: #fff; text-align: center;
            transform: rotate(45deg); font-weight: bold; font-size: 12px; padding: 5px 0;
            box-shadow: 0 2px 5px rgba(0,0,0,0.2);
        }
        .unpaid { background: #cc0000; }

    </style>
</head>
<body>

    {{-- RIBBON --}}
    <div class="ribbon">
        <div class="ribbon-content {{ $order->payment_status !== 'paid' ? 'unpaid' : '' }}">
            {{ $order->payment_status === 'paid' ? 'PAID' : 'UNPAID' }}
        </div>
    </div>

  {{-- HEADER --}}
    <table class="header-table">
        <tr>
            {{-- LEFT COLUMN --}}
            <td style="width: 60%; vertical-align: top;">
                @if($logoData)
                    {{-- Uses the embedded data string, works 100% of the time --}}
                    <img src="{{ $logoData }}" style="height: 60px; width: auto; margin-bottom: 10px;" alt="Orbita Logo">
                @else
                    {{-- Fallback Text --}}
                    <h1 style="color:#1a2b4b; margin:0; font-size: 24px;">ORBITA KENYA</h1>
                @endif
                
                <div class="company-info" style="margin-top: 5px;">
                    <p><strong>Showroom:</strong> {{ $showroom }}</p>
                    <p><strong>Office:</strong> {{ $office }}</p>
                    <p><strong>Email:</strong> {{ $email }} | <strong>Tel:</strong> {{ $phone }}</p>
                </div>
            </td>

            {{-- RIGHT COLUMN --}}
            <td style="width: 40%; text-align: right; vertical-align: top;">
                <div class="invoice-title" style="font-size: 32px; font-weight: bold; color: #d48d56;">INVOICE</div>
                <div class="invoice-meta">
                    <p><strong>Date:</strong> {{ $order->created_at->format('d/m/Y') }}</p>
                    <p><strong>Invoice No:</strong> #{{ str_pad($order->id, 7, '0', STR_PAD_LEFT) }}</p>
                </div>
            </td>
        </tr>
    </table>

    {{-- INFO BAR --}}
   <div class="info-bar">
    <table>
        <tr>
            <td style="width: 40%;">
                <div class="label">Invoiced To:</div>
                <div class="value">{{ $order->user->name ?? 'Guest Customer' }}</div>
                <div style="font-size: 11px; color: #555;">{{ $order->shipping_address }}</div>
            </td>
            {{-- NEW: Shipping Method Column --}}
            <td style="width: 30%; text-align: center;">
                <div class="label">Shipping Via:</div>
                <div class="value" style="color: #d48d56;">{{ strtoupper($shippingMethod) }}</div>
            </td>
            <td style="width: 30%; text-align: right;">
                <div class="label">Generated By:</div>
                <div class="value">{{ $generatedBy }}</div>
            </td>
        </tr>
    </table>
</div>

    {{-- PRODUCT TABLE --}}
    <table class="product-table">
        <thead>
            <tr>
                <th>Item Description</th>
                <th style="text-align: center;">Price</th>
                <th style="text-align: center;">Qty</th>
                <th style="text-align: right;">Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach($order->items as $item)
            <tr>
                <td>
                    <strong>{{ $item->product->name }}</strong>
                    <div style="font-size: 10px; color: #888;">{{ Str::limit($item->product->description, 60) }}</div>
                </td>
                <td style="text-align: center;">{{ number_format($item->unit_price, 2) }}</td>
                <td style="text-align: center;">{{ $item->quantity }}</td>
                <td style="text-align: right; font-weight: bold;">{{ number_format($item->unit_price * $item->quantity, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    {{-- FIXED FOOTER SECTION (Bank, Totals, Terms) --}}
    <div class="footer-wrapper">
        <table style="margin-bottom: 20px;">
            <tr>
                {{-- LEFT: BANK DETAILS (Previous Design) --}}
                <td style="width: 55%; padding-right: 30px; vertical-align: top;">
                    <div class="label" style="margin-bottom: 5px;">Payment Details:</div>
                    <div class="bank-box">
                        <strong>BANK:</strong> {{ $bankName }}<br>
                        <strong>ACC NAME:</strong> {{ $accName }}<br>
                        <strong>ACC NO:</strong> {{ $accNumber }}<br>
                        <strong>PAYBILL:</strong> N/A (Contact Admin)
                    </div>
                </td>

                {{-- RIGHT: TOTALS CALCULATION --}}
                <td style="width: 45%; vertical-align: top;">
                    <table class="totals-table">
                        <tr>
                            <td>SUBTOTAL:</td>
                            <td class="text-right">{{ number_format($subtotal, 2) }}</td>
                        </tr>
                        @if($discountAmount > 0)
                        <tr>
                            <td style="color: green;">DISCOUNT:</td>
                            <td class="text-right" style="color: green;">- {{ number_format($discountAmount, 2) }}</td>
                        </tr>
                        @endif
                        <tr>
                            <td>TAX ({{ $vatRate }}%):</td>
                            <td class="text-right">{{ number_format($taxAmount, 2) }}</td>
                        </tr>
                        <tr>
    <td>SHIPPING/HANDLING:</td>
    {{-- This will now show the real fee you entered --}}
    <td class="text-right">{{ number_format($shipping, 2) }}</td>
</tr>
                        <tr><td colspan="2" style="height: 5px;"></td></tr>
                        <tr class="grand-total">
                            <td>BALANCE DUE:</td>
                            <td class="text-right">KSH {{ number_format($grandTotal, 2) }}</td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>

        {{-- SEPARATOR & TERMS --}}
        <div class="divider-line"></div>
        
        <div class="label">Terms & Conditions:</div>
        <div class="terms-text">
            All products supplied by Orbita Kenya are covered by a one (1) year warranty against manufacturing defects from the date of purchase. This warranty does not cover damage resulting from misuse, negligence, improper installation, accidents, unauthorized modifications, or any form of human-caused damage. This invoice is system-generated by Orbita Kenya and serves as an official record of payment status. Ownership of the goods remains with Orbita Kenya until full payment is received.
        </div>
    </div>

    {{-- SIMPLE BOTTOM BAR --}}
    <div class="bottom-bar">
        This invoice is computer generated and is valid without a signature.
    </div>

</body>
</html>